/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Dimension;
import java.awt.Font;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

import controlador.Controlador;
import negocio.TDatos;

/**
 *
 * @author Ana Corral
 */
public class GUIMainImp extends GUIMain {

    /**
     * Creates new form GUIMainImp
     */
    public GUIMainImp() {
        initComponents();
        this.buttonGroup.add(jRadioButtonKMedias);
        this.buttonGroup.add(jRadioButtonLloyd);
        this.buttonGroup.add(jRadioButtonBayes);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setTitle("Algoritmo Método de Clasicación - Ana Laura Corral Descargue");
    	this.setMinimumSize(new Dimension(800,550));
        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        tituloMuestra = new javax.swing.JLabel();
        tituloInicializacion = new javax.swing.JLabel();
        tituloTest = new javax.swing.JLabel();
        tituloTipo = new javax.swing.JLabel();
        jTextFieldMuestra = new javax.swing.JTextField();
        jTextFieldInicializacion = new javax.swing.JTextField();
        jTextFieldTest = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jRadioButtonKMedias = new javax.swing.JRadioButton();
        jRadioButtonLloyd = new javax.swing.JRadioButton();
        jRadioButtonBayes = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        titulo.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Algoritmo Método de Clasificación");

        tituloMuestra.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tituloMuestra.setText("Nombre del archivo de la muestra:");

        tituloInicializacion.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tituloInicializacion.setText("Nombre del archivo para la inicializaciónn: ");

        tituloTest.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        tituloTest.setText("Nombre del archivo del test:");

        tituloTipo.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        tituloTipo.setText("Tipo:");

        jTextFieldMuestra.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jTextFieldMuestra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      

        jTextFieldInicializacion.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jTextFieldInicializacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldTest.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jTextFieldTest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      

        jButtonAceptar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonAceptar.setContentAreaFilled(false);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonCancelar.setContentAreaFilled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jRadioButtonKMedias.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jRadioButtonKMedias.setText("K-Medias");
        jRadioButtonKMedias.setContentAreaFilled(false);

        jRadioButtonLloyd.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jRadioButtonLloyd.setText("Lloyd");
        jRadioButtonLloyd.setContentAreaFilled(false);

        jRadioButtonBayes.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jRadioButtonBayes.setText("Bayes");
        jRadioButtonBayes.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonBayes)
                            .addComponent(jRadioButtonKMedias, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTest, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonLloyd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tituloTest, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tituloInicializacion, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tituloMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldMuestra)
                                .addComponent(jTextFieldInicializacion, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jTextFieldTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonKMedias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLloyd)
                    .addComponent(tituloTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonBayes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(titulo)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloInicializacion)
                        .addComponent(jTextFieldInicializacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(tituloTest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
       	String archivoMuestras = "", archivoInicializacion = "", archivoTest = "";
    	int nErrores = 0;
    	if(!this.jTextFieldMuestra.getText().matches("^(?!\\s*$).+")){
    		nErrores++;
    	}
    	else {
    		archivoMuestras = this.jTextFieldMuestra.getText();;
    	}
    	if(!this.jTextFieldInicializacion.getText().matches("^(?!\\s*$).+")){
    		nErrores++;
    	}
    	else {
    		archivoInicializacion = this.jTextFieldInicializacion.getText();;
    	}
    	if(!this.jTextFieldTest.getText().matches("^(?!\\s*$).+")){
    		nErrores++;
    	}
    	else {
    		archivoTest = this.jTextFieldTest.getText();;
    	}

	    if(this.jRadioButtonBayes.isSelected() && nErrores == 0) {
	    	TDatos tDatos = new TDatos(archivoMuestras, archivoInicializacion, archivoTest);
	    	Controlador.getInstance().accion(new Contexto(Events.BAYES, tDatos));
	    }
	    else if(this.jRadioButtonKMedias.isSelected() && nErrores == 0) {
	    	TDatos tDatos = new TDatos(archivoMuestras, archivoInicializacion, archivoTest);
	    	Controlador.getInstance().accion(new Contexto(Events.KMEDIAS, tDatos));
	    }
	    else if(this.jRadioButtonLloyd.isSelected() && nErrores == 0) {
	    	TDatos tDatos = new TDatos(archivoMuestras, archivoInicializacion, archivoTest);
	    	Controlador.getInstance().accion(new Contexto(Events.LLOYD, tDatos));
	    }
    	else {
    		JLabel label = new JLabel("<html><body>Hay que rellenar todos los campos</body></html>");
			label.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
			JOptionPane.showMessageDialog(null, label, "¡Cuidado!", JOptionPane.INFORMATION_MESSAGE);
    	}
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
    	JLabel label = new JLabel("<html><body><center>¡Nos Vemos!</center></body></html>");
		label.setFont(new Font("Rockwell Condensed", Font.BOLD, 20));
		JOptionPane.showMessageDialog(null, label, "¡Adios!", JOptionPane.INFORMATION_MESSAGE);
		System.exit(0);
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonBayes;
    private javax.swing.JRadioButton jRadioButtonKMedias;
    private javax.swing.JRadioButton jRadioButtonLloyd;
    private javax.swing.JTextField jTextFieldInicializacion;
    private javax.swing.JTextField jTextFieldMuestra;
    private javax.swing.JTextField jTextFieldTest;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloInicializacion;
    private javax.swing.JLabel tituloMuestra;
    private javax.swing.JLabel tituloTest;
    private javax.swing.JLabel tituloTipo;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actualizar(Contexto contexto) {
		int evento = contexto.getEvento();
		switch(evento) {
		case(Events.GUI_MAIN):
			this.setVisible(true);
		break;
		case(Events.LLOYD_OK):
			JLabel label1 = new JLabel((String)contexto.getDato());
			label1.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
			JOptionPane.showMessageDialog(null, label1, "¡Bien!", JOptionPane.INFORMATION_MESSAGE);
		break;
		case(Events.LLOYD_KO):
			if(contexto.getDato() == null) {
				JLabel label2 = new JLabel("<html><body>Fallo al cargar los archivos</body></html>");
				label2.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
				JOptionPane.showMessageDialog(null, label2, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
			}
			else {
				int res = (int) contexto.getDato();
				switch(res){
				case(-1):
					JLabel label4 = new JLabel("<html><body>Hay más vectores de inicializaciñon que clases</body></html>");
					label4.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label4, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-2):
					JLabel label5 = new JLabel("<html><body>Hay menos vectores de inicializaciñon que clases</body></html>");
					label5.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label5, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-3):
					JLabel label6 = new JLabel("<html><body>Los vectores de inicializacion no contienen numeros</body></html>");
					label6.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label6, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-4):
					JLabel label7 = new JLabel("<html><body>Los vectores de test no contienen numeros</body></html>");
					label7.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label7, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				}
			}
		break;
		case(Events.BAYES_OK):
			JLabel label3 = new JLabel((String)contexto.getDato());
			label3.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
			JOptionPane.showMessageDialog(null, label3, "¡Bien!", JOptionPane.INFORMATION_MESSAGE);
		break;
		case(Events.BAYES_KO):
			if(contexto.getDato() == null) {
				JLabel label4 = new JLabel("<html><body>Fallo al cargar los archivos</body></html>");
				label4.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
				JOptionPane.showMessageDialog(null, label4, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
			}
			else {
				int res = (int) contexto.getDato();
				switch(res){
				case(-1):
					JLabel label4 = new JLabel("<html><body>Hay más vectores de inicializaciñon que clases</body></html>");
					label4.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label4, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-2):
					JLabel label5 = new JLabel("<html><body>Hay menos vectores de inicializaciñon que clases</body></html>");
					label5.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label5, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-3):
					JLabel label6 = new JLabel("<html><body>Los vectores de inicializacion no contienen numeros</body></html>");
					label6.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label6, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-4):
					JLabel label7 = new JLabel("<html><body>Los vectores de test no contienen numeros</body></html>");
					label7.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label7, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				}
			}
		break;
		case(Events.KMEDIAS_OK):
			JLabel label5 = new JLabel((String)contexto.getDato());
			label5.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
			JOptionPane.showMessageDialog(null, label5, "¡Bien!", JOptionPane.INFORMATION_MESSAGE);
		break;
		case(Events.KMEDIAS_KO):
			if(contexto.getDato() == null) {
				JLabel label6 = new JLabel("<html><body>Fallo al cargar los archivos</body></html>");
				label6.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
				JOptionPane.showMessageDialog(null, label6, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
			}
			else {
				int res = (int) contexto.getDato();
				switch(res){
				case(-1):
					JLabel label4 = new JLabel("<html><body>Hay más vectores de inicializaciñon que clases</body></html>");
					label4.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label4, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-2):
					JLabel label8 = new JLabel("<html><body>Hay menos vectores de inicializaciñon que clases</body></html>");
					label8.setFont(new Font("Copperplate Gothic Bold", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label8, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-3):
					JLabel label6 = new JLabel("<html><body>Los vectores de inicializacion no contienen numeros</body></html>");
					label6.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label6, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				case(-4):
					JLabel label7 = new JLabel("<html><body>Los vectores de test no contienen numeros</body></html>");
					label7.setFont(new Font("Rockwell Condensed", Font.BOLD, 25));
					JOptionPane.showMessageDialog(null, label7, "¡Cuidado!", JOptionPane.WARNING_MESSAGE);
				break;
				}
			}
		break;
		}
	}
}
